### PR TITLE
React: Refactor file select input to render minimal options

### LINKED ISSUE #617: Unlinked files component should render only a portion of available files
A large number of unlinked files will tax the browser in its current implementation and significantly slow down or crash the app. Unlinked files should be rendered in chunks or hidden behind a search interface.

### PR DESCRIPTION
**Pull request by cklamann**
closes #617 

* limit autocomplete panel display of unlinked files to 25
* show selected files in tags

### CODE REVIEW

File: react/src/components/FileLinkingComponent.tsx [hunk 1]
```diff
@@ -185,124 +160,69 @@ export default function FileLinkingComponent(props: {
...
-                                                ? (filteredOptions = [])
-                                                : (filteredOptions = [
-                                                      {
-                                                          title: "Select all",
-                                                          inputValue: "Select all",
-                                                      },
-                                                      ...filtered,
-                                                  ]);
-                                            return filteredOptions;
+                                        style={{ width: "400px" }}
```
Comment (kevinlul) [inline react/src/components/FileLinkingComponent.tsx:174]: Once this is ready stuff like this should be in the `makeStyles`

**Review by kevinlul — COMMENTED** [review]
This looks great! On the datasets page, after updating the list of linked files and committing to the backend, the files for that row in the frontend aren't updated until a refresh though.
