### PR TITLE
React: Fix the bug in dataset modal to get options for Dataset types

### LINKED ISSUE #1100: Bug in dataset modal for datasets of type RES
Using seed data, on the Datasets page, when we toggle the edit mode in the Dataset modal with a dataset of type `RES`, the web interface will go blank and the following error will be shown: 
Screen Shot 2022-04-12 at 11 51 12 AM
Screen Shot 2022-04-12 at 11 51 38 AM
Screen Shot 2022-04-12 at 11 51 52 AM

These errors do not occur with datasets of other types. 

- [ ] Look at the raw JSON representation of the affected datasets.
- [ ] Maybe there's a missing field.

### PR DESCRIPTION
**Pull request by jennyziyi-xu**
Closes #1100

### CODE REVIEW

File: react/src/components/FieldDisplayEditable.tsx [hunk 1]
```diff
@@ -87,8 +93,9 @@ function EnhancedTextField({
             textFieldProps.onChange = (e: TextFieldEvent) => {
                 onEdit(field.fieldName, e.target.value === "" ? null : e.target.value);
             };
+
             children = [
-                ...enums[getFieldInEnums(field.fieldName)]?.map((option: string) => (
+                enums[getFieldInEnums(field.fieldName)]?.map((option: string) => (
```
Comment (kevinlul) [inline react/src/components/FieldDisplayEditable.tsx:98]: Dropping the spread operator means we get an array with one element that is another array, are you sure? I don't recall why the `[...thing]` pattern was used here. `.map` does already return an array that isn't a reference to an existing one.

File: react/src/components/FieldDisplayEditable.tsx [hunk 2]
```diff
@@ -50,7 +50,13 @@ function EnhancedTextField({
     onEdit: (fieldName: string, value: boolean | string | null | UnlinkedFile[]) => void;
 }) {
     const [filePrefix, setFilePrefix] = useState<string>("");
-    const enums = useAPIInfoContext()?.enums;
+    const apiInfo = useAPIInfoContext() ?? undefined;
+    var enums;
+    if (apiInfo) {
+        enums = apiInfo.enums;
+        enums["DatasetType"] = Object.keys(apiInfo.dataset_types);
+    }
```
Comment (kevinlul) [inline react/src/components/FieldDisplayEditable.tsx:58]: You could copy over the `hackedTogetherEnums` thing so this is memoized.

**Review by kevinlul — CHANGES_REQUESTED** [review]

**Review by kevinlul — APPROVED** [review]
LGTM!
